version: '3.8'

services:
  # MySQL Database Service
  database:
    image: mysql:5.7
    container_name: auth_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_test_security
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    networks:
      - auth_test_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # PHP Apache Web Server Service
  webserver:
    build: .
    container_name: auth_test_web
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - auth_test_network
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=auth_test_security

  # PHPMyAdmin for Database Management (Optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: auth_test_phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - auth_test_network

volumes:
  mysql_data:
    driver: local

networks:
  auth_test_network:
    driver: bridge 